---
- hosts: server2
  tasks:
   - name: Set variables
     set_fact:
         data_bridge: "private-br"
         ip_databr: "172.16.16.1/25"
   
   - shell: ovs-vsctl add-br {{ data_bridge }}
     sudo: yes

   - shell: ip addr add {{ ip_databr }} dev {{ data_bridge }}
     sudo: yes
