---
- hosts: server2 
  tasks:
    - name: Execute simple command
      command: ovs-vsctl show
      sudo: yes
      register: output

    - name: Show output      
      debug: msg="{{ output.stdout }}"
